# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows

environment:

    global:
        PYTHON: "C:\\conda"
        MINICONDA_VERSION: "latest"
        CONDA_DEPENDENCIES: "scipy matplotlib numpy astropy ipython"
        ASTROPY_USE_SYSTEM_PYTEST: 1
        CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"
        PYTHON_ARCH: "64" # needs to be set for CMD_IN_ENV to succeed. If a mix
                          # of 32 bit and 64 bit builds are needed, move this
                          # to the matrix section.

    matrix:

        - PYTHON_VERSION: "3.5"
          NUMPY_VERION: "stable"
          ASTROPY_VERSION: "stable"

        - PYTHON_VERSION: "3.6"
          NUMPY_VERSION: "stable"
          ASTROPY_VERSION: "stable"

        - PYTHON_VERSION: "3.7"
          NUMPY_VERSION: "stable"
          ASTROPY_VERSION: "stable"

        - PYTHON_VERSION: "3.7"
          NUMPY_VERSION: "development"
          CONDA_DEPENDENCIES: "scipy glymur"
          CONDA_CHANNELS: "conda-forge astrofrog"
          PIP_DEPENDENCIES: "requests pyparsing"
          CONDA_CHANNEL_PRIORITY: "True"
          DEBUG: "True"

matrix:
    fast_finish: true


platform:
    -x64

# os: Visual Studio 2015 Update 2

install:
    - "git submodule update --init --recursive"
    - "git clone git://github.com/astropy/ci-helpers.git"
    - "powershell ci-helpers/appveyor/install-miniconda.ps1"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "activate test"
    - "conda --version"
    - "python --version"

# Not a .NET project, we build in the install step instead
build: false

test_script:
    - "%CMD_IN_ENV% python setup.py test"
